### ISSUE TITLE
Non-auxillary usages of have/has/be 

### ISSUE THREAD

**Issue by danyaljj** [nafitzgerald/nrl-qasrl#11]
Hello there! 

The paper says: "We identify verbs by POS tag, with heuristics to filter out auxiliary verbs while retaining non-auxiliary uses of “have” and “do.”"

I just tried to parse the following sentences (where has/is are used as the main verb =non-auxilary) in [the demo](http://demo.qasrl.org/), and it doesn't seem to give anything. 

- Alice has two blue bags.  
- Jack has a panda.  
- Sky is blue.

**Comment by julianmichael** [comment]
Hi sorry I didn't see this earlier. We implemented that logic for the data-gathering portion but not the demo (which was put together a bit last-minute). If you're working with the QA-SRL Bank dataset you don't need to worry about it since the set of verbs is provided. But regardless, you can find the code implementing the heuristics [here](https://github.com/julianmichael/qasrl-crowdsourcing/blob/v0.1.0/qasrl-crowd/src-jvm/qasrl/crowd/QASRLAnnotationPipeline.scala#L56).

You might notice that the verbs are sometimes attributed the wrong inflections in the demo. That doesn't happen nearly as often in the dataset because there are some better heuristics for that built into the data pipeline as well.

Sorry that wasn't all clear. Hope this helps!

**Comment by danyaljj** [comment]
Got it, thanks!
