### ISSUE TITLE
Never-lazy datareader

### ISSUE THREAD

**Issue by nelson-liu** [nafitzgerald/nrl-qasrl#6]
Hi!

I notice that you explicitly forbade your datareader from being lazy (https://github.com/nafitzgerald/nrl-qasrl/blob/master/nrl/data/dataset_readers/qasrl_reader.py#L35). I'm curious: is there a particular reason for this?

Thanks!

**Comment by nafitzgerald** [comment]
To be perfectly honest, it's simply because I wrote this code before AllenNLP had the lazy option, and when I was updating the code for the newer releases of AllenNLP I just set it to false in order to keep as much as possible of the execution the same. I don't believe there would be any benefit from running it lazily, unless I'm missing something?

**Comment by nelson-liu** [comment]
ah ok, I agree with you --- was just wondering. thanks!
